image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - zola
environment:
  site: finnala.srht.site
tasks:
  - build: |
      cd personal-website
      zola build
  - package: |
      cd personal-website
      tar -C public -cvz . > ../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
